Repository FRONTENDSCHOOL6/react-project-7, pull requests merged in 2023-09, with the labels that each got.

#27 랜딩페이지 - 레이아웃 구현
  package.json
  pnpm-lock.yaml
  public/assets/onboarding/arrow-down.svg
  public/assets/onboarding/arrow-up.svg
  public/assets/onboarding/no1-tving.svg
  rome.json
  src/pages/OnBoarding.jsx
  src/pages/onboarding.module.css
  src/styles/index.css
Labels: ✨ feat

#30 [Search] 검색페이지 기능 구현
  public/assets/logo-dark.svg
  public/assets/x-circle-icon.svg
  public/assets/x-icon.svg
  src/components/common/Spinner.jsx
  src/layout/RootLayout.jsx
  src/pages/Search.jsx
  src/pages/Search.module.css
  src/routes/route.jsx
  src/styles/index.css
  src/utils/getPbImageURL.js
Labels: ➕ add, ✨ feat, 🕹️ react, 🪩 javascript

#37 [Search] 디렉토리명 변경
  src/components/search/contents/RealtimeSearch.jsx
  src/components/search/contents/RecentView.jsx
  src/components/search/util/CurrentTime.jsx
  src/components/search/util/HighlightedText.jsx
  src/pages/Search.jsx
Labels: 🐛 bug, ✏️ modify

#38 [FindId] 아이디 찾기 페이지 기능 추가 및 기타 이미지 업로드 (추후 기능보완 필요)
  public/assets/clear-all.svg
  public/assets/popup-menu.svg
  public/assets/small-gray-check.svg
  public/assets/small-red-check.svg
  src/pages/FindId.jsx
Labels: ➕ add, 🎨 css, ✨ feat

#42 [OnBoarding] 랜딩페이지 컴포넌트 분리 및 이미지 불러오기 변경
  .eslintrc.cjs
  public/assets/dongwon-uquiz.webp
  public/assets/exorcism.webp
  public/assets/uquiz.webp
  src/pages/Home.jsx
  src/pages/Home.module.css
  src/pages/LoopSlide.jsx
  src/pages/MainList.jsx
  src/pages/OnBoarding.jsx
  src/pages/onboarding.module.css
  src/styles/index.css
Labels: 🐛 bug, 🎨 css, ✨ feat, 🛠️ fix, 👀 refactor, 🪩 javascript

#43 [Header] 이미지 불러오기 변경
  src/layout/Header.jsx
  src/layout/SimpleHeader.jsx
Labels: 🐛 bug, 🛠️ fix

#44 [Footer] 이미지 불러오기 변경
  src/layout/Footer.jsx
Labels: 🐛 bug, 🛠️ fix

#45 [Home] 메인페이지 컴포넌트 분리 및 이미지 불러오기 변경
  src/pages/Home.jsx
  src/pages/Home.module.css
  src/pages/MainBanner.jsx
  src/pages/MainList.jsx
  src/styles/index.css
Labels: 🐛 bug, 🎨 css, ✨ feat, 🛠️ fix, 👀 refactor, 🪩 javascript

#46 [Common] 일부 유틸 함수 추가 및 파일명 변경
  src/hooks/useStorage.js
  src/pages/Search.jsx
  src/store/authStore.js
  src/store/searchStore.js
  src/utils/keyDown.js
  src/utils/removeQuotes.js
  src/utils/separateComma.js
Labels: ➕ add, ✏️ modify

#48 [Membership] 멤버십 페이지 레이아웃 구현
  public/assets/recommend.svg
  src/components/membership/MembershipTable.jsx
  src/components/membership/MembershipTitle.jsx
  src/components/membership/MembershipType.jsx
  src/components/membership/MembershipTypes.jsx
  src/components/membership/MembershipWarning.jsx
  src/pages/Membership.jsx
Labels: ➕ add, ✨ feat

#49 [Profile] 프로필 페이지 레이아웃 구현 #47
  public/assets/default-profile.png
  src/layout/RootLayout.jsx
  src/pages/EditProfile.jsx
  src/pages/EditProfiles.jsx
  src/pages/EditProfiles.module.css
  src/pages/Profile.jsx
  src/routes/route.jsx
Labels: ➕ add, ✨ feat

#55 [Header] 검색 페이지에서의 아이콘 변경
  public/assets/headerX.svg
  src/layout/Header.jsx
Labels: ➕ add, ✨ feat, 🕹️ react, 🪩 javascript

#57 [Profile] 프로필 페이지 전환 및 편집 기능 추가
  src/layout/Header.jsx
  src/pages/EditProfile.jsx
  src/pages/EditProfiles.jsx
  src/pages/EditProfiles.module.css
  src/pages/Profile.jsx
  src/pages/SignUp.jsx
  src/routes/route.jsx
Labels: ➕ add, ✨ feat, 🕹️ react, 🪩 javascript

#56 [OnBoarding, 공통] 랜딩 페이지 반응형 레이아웃 일부 수정, 공통 폰트 사이즈 수정
  public/assets/tving-symbol.svg
  src/pages/LoopSlide.jsx
  src/pages/OnBoarding.jsx
  src/pages/onboarding.module.css
  src/styles/index.css
Labels: 🐛 bug, 🎨 css, 🛠️ fix

#59 [Header] hover 이벤트의 버그 수정
  src/layout/Header.jsx
Labels: 🐛 bug, 🛠️ fix

#61 [OnBoarding] 반응형 수정 및 이미지 파일 오류 수정
  src/pages/LoopSlide.jsx
  src/pages/OnBoarding.jsx
  src/pages/onboarding.module.css
Labels: 🐛 bug, 🎨 css, 🛠️ fix, 👀 refactor

#62 [Home] 메인페이지 레이아웃 수정
  public/assets/big-check.svg
  public/assets/bigbang.png
  public/assets/headerX.svg
  public/assets/kbo.jpeg
  public/assets/tving-login.svg
  public/assets/tving-symbol.svg
  public/assets/ufc.jpeg
  src/layout/Header.jsx
  src/layout/Header.module.css
  src/pages/CategoryNav.jsx
  src/pages/Contents.jsx
  src/pages/EditProfile.jsx
  src/pages/EditProfiles.jsx
  src/pages/EditProfiles.module.css
  src/pages/FailedFindId.jsx
  src/pages/FindId.jsx
  src/pages/Home.jsx
  src/pages/Home.module.css
  src/pages/MainBanner.jsx
  src/pages/MainList.jsx
  src/pages/Movie.jsx
  src/pages/Movie.module.css
  src/pages/OnBoarding.jsx
  src/pages/Profile.jsx
  src/pages/Program.jsx
  src/pages/Program.module.css
  src/pages/ProgramNav.jsx
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
  src/pages/SuccessFindId.jsx
  src/pages/failedfindid.module.css
  src/pages/findid.module.css
  src/pages/onboarding.module.css
  src/pages/successfindid.module.css
  src/routes/route.jsx
  src/store/authStore.js
  src/store/idStore.js
  src/styles/index.css
Labels: ➕ add, 🎨 css, ✨ feat

#63 [Profile] 프로필 변경, ProtectRoute 설정
  public/assets/big-check.svg
  public/assets/bigbang.png
  public/assets/headerX.svg
  src/App.jsx
  src/components/common/Spinner.jsx
  src/layout/Header.jsx
  src/pages/CategoryNav.jsx
  src/pages/Contents.jsx
  src/pages/EditProfile.jsx
  src/pages/EditProfiles.jsx
  src/pages/EditProfiles.module.css
  src/pages/OnBoarding.jsx
  src/pages/Profile.jsx
  src/pages/SignIn.jsx
  src/routes/ProtectRoute.jsx
  src/routes/route.jsx
  src/store/authStore.js
  src/store/useProfileStore.js
Labels: ➕ add, 🐛 bug, ✨ feat, 🕹️ react, 🪩 javascript

#64 🐛 [fix] 비동기 데이터 렌더링 에러 해결
  src/layout/Header.jsx
  src/store/authStore.js
Labels: 🐛 bug

#68 [Common] ProtectRoute 설정 오류 해결
  src/layout/Header.jsx
  src/pages/EditProfile.jsx
  src/pages/EditProfiles.jsx
  src/pages/Profile.jsx
  src/pages/SignIn.jsx
  src/routes/ProtectRoute.jsx
  src/routes/route.jsx
  src/store/useAuthStore.js
Labels: 🐛 bug, 🛠️ fix

#67 [Feat] SNS 연동 로그인 페이지 레이아웃 및 카카오톡 연동 로그인 기능
  public/assets/apple-login.svg
  public/assets/cjone-login.png
  public/assets/facebook-login.svg
  public/assets/kakao-login.svg
  public/assets/naver-login.svg
  public/assets/tving-login.svg
  public/assets/twitter-login.svg
  src/pages/SignInList.jsx
  src/pages/SignInList.module.css
  src/routes/route.jsx
Labels: ➕ add, ✨ feat

#76 🙌 [merge] 경로 설정 변경
  src/pages/OnBoarding.jsx
Labels: 🤝 discussed

#78 ✨ [feat] 아이디 찾기 기능 및 레이아웃 추가
  src/pages/FailedFindId.jsx
  src/pages/FailedFindId.module.css
  src/pages/FindId.jsx
  src/pages/FindId.module.css
  src/pages/SignIn.jsx
  src/pages/SuccessFindId.jsx
  src/pages/SuccessFindId.module.css
  src/routes/route.jsx
  src/store/idStore.js
Labels: ➕ add, 🎨 css, ✨ feat, 📢 help

#79 🐛 [fix] 로그인 유지, 프로필 유지 관련 에러
  src/components/profile/Profile.module.css
  src/components/profile/ProfileEditButton.jsx
  src/components/profile/ProfileItem.jsx
  src/components/profile/ProfileList.jsx
  src/components/profile/ProfileTitle.jsx
  src/layout/Header.jsx
  src/pages/Profile.jsx
  src/routes/ProtectRoute.jsx
  src/routes/route.jsx
Labels: 🛠️ fix, ✏️ modify

#82 🐛 [fix] 로그인 관련 에러 수정
  src/layout/Header.jsx
Labels: 🐛 bug, 🛠️ fix

#83 [Header] route 변경, 레이아웃 수정
  src/layout/Header.jsx
  src/layout/Header.module.css
  src/layout/RootLayout.jsx
Labels: 🐛 bug, 🎨 css, 🛠️ fix

#84 [Home] 스와이퍼 버튼 컴포넌트 생성
  src/components/common/SwiperButton.jsx
Labels: ✨ feat

#85 [Home] 메인페이지 컴포넌트 분리
  src/components/common/SwiperButton.jsx
  src/components/home/EventBanner.jsx
  src/components/home/Home.module.css
  src/components/home/MainBanner.jsx
  src/components/home/MainList.jsx
  src/components/home/PopularList.jsx
  src/pages/Home.jsx
  src/store/useContentsStore.js
Labels: 👀 refactor, 🕹️ react

#87 [Profile] 프로필 페이지 컴포넌트 분리 및 모듈 css 적용
  src/components/common/Button/Button.module.css
  src/components/common/Button/Buttons.jsx
  src/components/editProfile/ButtonSection.jsx
  src/components/editProfile/EditProfile.module.css
  src/components/editProfile/EditProfileSection.jsx
  src/components/editProfiles/ButtonSection.jsx
  src/components/editProfiles/EditProfiles.module.css
  src/components/editProfiles/ProfileItem.jsx
  src/components/editProfiles/ProfileList.jsx
  src/components/editProfiles/ProfileListSection.jsx
  src/components/profile/Profile.module.css
  src/components/profile/ProfileEditButton.jsx
  src/components/profile/ProfileItem.jsx
  src/components/profile/ProfileList.jsx
  src/components/profile/ProfileTitle.jsx
  src/layout/Header.jsx
  src/layout/RootLayout.jsx
  src/pages/EditProfile.jsx
  src/pages/EditProfiles.jsx
  src/pages/EditProfiles.module.css
  src/pages/Profile.jsx
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
  src/routes/route.jsx
Labels: ➕ add, ✨ feat, 👀 refactor

#88 [OnBoarding] 랜딩페이지 컴포넌트 분리
  src/components/onBoarding/Find.jsx
  src/components/onBoarding/JoinMain.jsx
  src/components/onBoarding/LoopSlide.jsx
  src/components/onBoarding/OnBoarding.module.css
  src/components/onBoarding/OnlyTaing.jsx
  src/components/onBoarding/QnA.jsx
  src/components/onBoarding/Smart.jsx
  src/components/onBoarding/StartButton.jsx
  src/components/onBoarding/StartNow.jsx
  src/components/onBoarding/Together.jsx
  src/components/onBoarding/Youtube.jsx
  src/pages/OnBoarding.jsx
Labels: ✨ feat, 👀 refactor, 🕹️ react

#89 [FindId] 아이디 찾기 페이지 컴포넌트 분리
  src/components/findid/ConfirmButton.jsx
  src/components/findid/ConfirmButton.module.css
  src/components/findid/InputForm.jsx
  src/components/findid/InputForm.module.css
  src/components/findid/LoginButton.jsx
  src/components/findid/LoginButton.module.css
  src/pages/FailedFindId.jsx
  src/pages/FailedFindId.module.css
  src/pages/FindId.jsx
  src/pages/FindId.module.css
  src/pages/SuccessFindId.jsx
  src/pages/SuccessFindId.module.css
Labels: ➕ add, 🎨 css, 👀 refactor

#91 [Header] 경로 수정 및 컴포넌트 분리
  src/components/header/Header.module.css
  src/components/header/HoverBox.jsx
  src/components/header/headerContents.jsx
  src/layout/Header.jsx
  src/layout/SimpleHeader.jsx
Labels: 👀 refactor

#92 [OnBoarding] 경로 문제 및 오류 수정
  src/components/onBoarding/Find.jsx
  src/components/onBoarding/JoinMain.jsx
  src/components/onBoarding/OnlyTaing.jsx
  src/components/onBoarding/QnA.jsx
  src/components/onBoarding/Smart.jsx
  src/components/onBoarding/StartNow.jsx
  src/components/onBoarding/Together.jsx
  src/components/onBoarding/Youtube.jsx
Labels: 👀 refactor

#94 [Category] 컴포넌트 분리 작업
  src/components/category/Category.module.css
  src/components/category/MovieContent.jsx
  src/components/category/MovieNav.jsx
  src/components/category/NavButton.jsx
  src/components/category/ProgramContent.jsx
  src/components/category/ProgramNav.jsx
  src/pages/CategoryNav.jsx
  src/pages/Movie.jsx
  src/pages/MovieNav.jsx
  src/pages/Program.jsx
  src/pages/Program.module.css
  src/pages/ProgramNav.jsx
Labels: 👀 refactor

#95 [Exception] 예외 처리 페이지 레이아웃 및 스타일링
  public/assets/not-found.svg
  src/pages/NotFound.jsx
  src/pages/NotFound.module.css
  src/routes/route.jsx
Labels: ➕ add, 🎨 css, ✨ feat

#96 [Exception] 로딩페이지 구현
  src/App.jsx
  src/components/common/PendingPage.jsx
  src/pages/NotFound.module.css
Labels: ➕ add, 🎨 css, ✨ feat

#97 [Search] 검색 페이지 컴포넌트 분리 및 모듈 css 적용
  src/components/common/SwiperButton.jsx
  src/components/search/Search.module.css
  src/components/search/contents/ListSection.jsx
  src/components/search/contents/SearchResult.jsx
  src/components/search/contents/SearchSection.jsx
  src/components/search/contents/SearchedResultSwiper.jsx
  src/components/search/contents/SearchingResultSwiper.jsx
  src/pages/Search.jsx
  src/styles/index.css
Labels: ➕ add, 👀 refactor

#98 [Search] 스와이퍼 일부 수정
  src/components/search/contents/SearchedResultSwiper.jsx
Labels: 🛠️ fix, ✏️ modify

#99 [SignIn] 로그인 페이지 컴포넌트 분리
  src/components/signin/SubmitButton.jsx
  src/components/signin/SubmitButton.module.css
  src/pages/SignIn.jsx
  src/pages/SignIn.module.css
Labels: ➕ add, 🎨 css, 👀 refactor, 🕹️ react

#101 [Exception] Spinner 스타일 변경
  src/components/common/Spinner.jsx
Labels: ➕ add, 🎨 css, 👀 refactor

#107 [Header] 프로필 이미지 비율 유지
  src/components/header/Header.module.css
  src/layout/Header.jsx
Labels: 🐛 bug, 🎨 css, 🛠️ fix

#108 [Search] 검색 페이지 리팩토링
  src/components/search/Search.module.css
  src/components/search/contents/RealtimeSearch.jsx
  src/components/search/contents/RecentView.jsx
  src/components/search/contents/SearchResult.jsx
  src/components/search/contents/SearchedResultSwiper.jsx
  src/components/search/contents/SearchingResultSwiper.jsx
  src/pages/SignInList.jsx
  src/store/searchStore.js
  src/styles/index.css
Labels: ✨ feat, 🛠️ fix, 👀 refactor

#109 [Profile] 프로필 관련 페이지 일부 css 수정
  src/components/editProfile/EditProfileSection.jsx
  src/components/editProfiles/ProfileItem.jsx
  src/components/editProfiles/ProfileList.jsx
  src/components/editProfiles/ProfileListSection.jsx
  src/components/membership/Membership.module.css
  src/components/profile/ProfileEditButton.jsx
  src/components/profile/ProfileItem.jsx
  src/components/profile/ProfileList.jsx
  src/pages/EditProfile.jsx
  src/pages/EditProfiles.jsx
  src/pages/Profile.jsx
Labels: 🎨 css, ✏️ modify

#110 [Home] Swiper button 수정
  src/components/home/EventBanner.jsx
  src/components/home/MainBanner.jsx
  src/components/home/MainList.jsx
  src/components/home/PopularList.jsx
  src/pages/Home.jsx
  src/styles/index.css
Labels: 🎨 css, 🛠️ fix, 👀 refactor, 🕹️ react

#111 [Category] swiper button 관련 수정
  src/components/category/MovieNav.jsx
  src/components/category/NavButton.jsx
  src/components/category/ProgramNav.jsx
Labels: ➕ add, 🐛 bug, ✨ feat, 🛠️ fix, 👀 refactor, 🕹️ react

#114 [Snslogin] SNS 연동 로그인 페이지 컴포넌트 분리 및 헬멧 코드 추가
  public/assets/metaImgSnsLogin.png
  src/components/snslogin/SnsLogin.jsx
  src/components/snslogin/SnsLogin.module.css
  src/pages/SignInList.jsx
  src/pages/SignInList.module.css
Labels: ➕ add, 👀 refactor, 🕹️ react

#115 [Home] meta 태그 이미지 경로 수정
  src/pages/Home.jsx
Labels: ✏️ modify

#116 [Category] meta 태그 이미지 경로 수정
  src/components/category/NavButton.jsx
  src/pages/Movie.jsx
  src/pages/Program.jsx
Labels: ✏️ modify

#117 [OnBoarding] meta 태그 이미지 경로 수정
  src/pages/OnBoarding.jsx
Labels: ✏️ modify

#118 [Search] 메타 태그 추가
  public/assets/search-result.png
  src/components/header/Header.module.css
  src/components/header/LogoutPopUp.jsx
  src/components/header/ProfileModal.jsx
  src/components/search/contents/SearchingResultList.jsx
  src/layout/Header.jsx
  src/layout/RootLayout.jsx
  src/pages/Search.jsx
  src/pages/SignInList.jsx
  src/pages/search-result.png
Labels: ➕ add, 👀 refactor

#119 [membership] 멤버십 페이지 메타 태그 추가
  src/pages/Membership.jsx
Labels: ➕ add, 👀 refactor

#122 [profile] 프로필 관련 페이지 메타태그 추가
  src/layout/Header.jsx
  src/pages/EditProfile.jsx
  src/pages/EditProfiles.jsx
  src/pages/Profile.jsx
Labels: ➕ add, 👀 refactor

#121 [SIgnIn, FindId ] 로그인, 아이디 찾기 관련 페이지 헬멧 코드 추가
  public/assets/metaImgFailedFindId.png
  public/assets/metaImgFindId.png
  public/assets/metaImgLogin.png
  public/assets/metaImgSuccessFindId.PNG
  src/pages/FailedFindId.jsx
  src/pages/FindId.jsx
  src/pages/SignIn.jsx
  src/pages/SuccessFindId.jsx
Labels: 📄 doc s, ✏️ modify

#123 ♻️ [feat] sns 로그인 페이지 컴포넌트 수정 및 누락 기능 보완
  src/components/snslogin/SnsLogin.jsx
  src/components/snslogin/SnsLogin.module.css
  src/pages/SignIn.jsx
  src/pages/SignInList.jsx
Labels: ➕ add, ✏️ modify, 👀 refactor

#125 🐛 [fix] 프로필 이미지 비율 수정
  src/components/header/Header.module.css
Labels: 🐛 bug, 🎨 css, 🛠️ fix

#128 [search] 주석, 콘솔 삭제
  src/components/search/contents/ListSection.jsx
  src/components/search/contents/RealtimeSearch.jsx
  src/components/search/contents/RecentView.jsx
  src/components/search/contents/SearchResult.jsx
  src/components/search/contents/SearchSection.jsx
  src/components/search/contents/SearchedResultSwiper.jsx
Labels: ✏️ modify

#130 [Refector] 로그인, 아이디 찾기 관련 페이지들 불필요 코드 및 주석 삭제
  public/assets/metaImgSignUp.png
  src/components/Form/FormInput.jsx
  src/components/Form/FormInput.module.css
  src/components/Form/FormTitle.jsx
  src/components/Form/FormTitle.module.css
  src/pages/FindId.jsx
  src/pages/SignIn.jsx
  src/pages/SignInList.jsx
  src/pages/SignUp.jsx
  src/pages/SignUp.module.css
  src/pages/SuccessFindId.jsx
Labels: 🗑️ delete, 👀 refactor

#131 [Detail] 상세페이지 코드 수정
  src/components/detail/DetailData.jsx
  src/components/detail/EditReview.jsx
  src/components/detail/Review.jsx
  src/components/detail/ShareLink.jsx
  src/components/detail/SimilarVideo.jsx
  src/pages/Favorite.jsx
Labels: ✏️ modify
